import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/libs/utils";
import TanstackProvider from "@/providers/TanstackProvider";
import { Toaster } from "react-hot-toast";
import "@/styles/globals.css";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "ADS Frontend Test | Alfan Olivan",
  description: "Generated by create next app 13",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("min-h-screen scroll-smooth bg-gray-50 font-sans antialiased", fontSans.className)}>
        <Toaster position="top-right" reverseOrder={false} />
        <TanstackProvider>
          <main className="container min-h-screen px-4 py-8 text-gray-900 md:px-16 md:py-10">{children}</main>
        </TanstackProvider>
      </body>
    </html>
  );
}
